# GNU Make workspace makefile autogenerated by Premake

ifndef config
  config=debug
endif

ifndef verbose
  SILENT = @
endif

ifeq ($(config),debug)
  sokol_config = debug
  glfw_config = debug
  game_config = debug
endif
ifeq ($(config),release)
  sokol_config = release
  glfw_config = release
  game_config = release
endif

PROJECTS := sokol glfw game

.PHONY: all clean help $(PROJECTS) 

all: $(PROJECTS)

sokol:
ifneq (,$(sokol_config))
	@echo "==== Building sokol ($(sokol_config)) ===="
	@${MAKE} --no-print-directory -C ext -f sokol.make config=$(sokol_config)
endif

glfw:
ifneq (,$(glfw_config))
	@echo "==== Building glfw ($(glfw_config)) ===="
	@${MAKE} --no-print-directory -C ext -f glfw.make config=$(glfw_config)
endif

game: glfw sokol
ifneq (,$(game_config))
	@echo "==== Building game ($(game_config)) ===="
	@${MAKE} --no-print-directory -C src -f Makefile config=$(game_config)
endif

clean:
	@${MAKE} --no-print-directory -C ext -f sokol.make clean
	@${MAKE} --no-print-directory -C ext -f glfw.make clean
	@${MAKE} --no-print-directory -C src -f Makefile clean

help:
	@echo "Usage: make [config=name] [target]"
	@echo ""
	@echo "CONFIGURATIONS:"
	@echo "  debug"
	@echo "  release"
	@echo ""
	@echo "TARGETS:"
	@echo "   all (default)"
	@echo "   clean"
	@echo "   sokol"
	@echo "   glfw"
	@echo "   game"
	@echo ""
	@echo "For more information, see https://github.com/premake/premake-core/wiki"